USE hr;

SELECT * 
FROM employees
WHERE ADDRESS LIKE '%Elgin,IL%';

SELECT *
FROM EMPLOYEES
WHERE B_DATES like '197$';

SELECT *
FROM EMPLOYEES 
WHERE(SALARY BETWEEN 60000 AND 70000)
AND emp_ID = 5;

SELECT *
FROM EMPLOYEES 
ORDER BY EMP_ID DESC;

SELECT DEP_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*), AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING COUNT(*) < 4
ORDER BY AVG_SALARY;

